version: '2.1'
services:
  mongodb:
    image: "mongo"
    ports:
     - "13266:27017"
  mysqldb:
    image: "mysql:5.5.60"
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbnuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "10.0.3.93"]
      timeout: 20s
      retries: 5
    ports:
     - "17066:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysqldb
    ports:
      - "2266:80"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: 10.0.3.93
    depends_on:
      mysqldb:
        condition: service_healthy
  backend:
    build: ./node-backend/
    ports:
      - "12566:6200"
    volumes:
      - ./node-backend:/usr/src/app
      - ./data:/usr/src/app/data
    depends_on:
      mysqldb:
        condition: service_healthy
      mongodb:
        condition: service_started
  frontend:
    build: ./react-frontend/
    ports:
      - "12866:3000"
    volumes:
      - ./react-frontend:/usr/src/app
    depends_on:
      - backend
